#!/usr/bin/env python3
"""
Auto-Snapshot Generator
Creates automatic snapshots of the memory system state!
"""

from datetime import datetime
from pathlib import Path

BASE = Path("/home/openclaw/.openclaw/workspace-mochi")
SNAPSHOT_FILE = BASE / "memory" / "snapshots.md"

def generate_snapshot():
    """Generate a system state snapshot."""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date = datetime.now().strftime("%Y-%m-%d")
    
    # Gather stats
    memory_files = len(list((BASE / "memory").glob("*.md")))
    skills = len(list((BASE / "skills").glob("*/SKILL.md")))
    
    # Count folders
    people = len(list((BASE / "memory" / "people").glob("*.md")))
    decisions = len(list((BASE / "memory" / "decisions").glob("*.md")))
    mistakes = len(list((BASE / "memory" / "mistakes").glob("*.md")))
    improvements = len(list((BASE / "memory" / "improvements").glob("*.md")))
    backups = len(list((BASE / "memory" / "backups").glob("*.zip")))
    
    # Count rules
    rules = 10  # Always 10 in SOUL.md
    
    snapshot = f"""
---

## {date} - Auto Snapshot

| Stat | Value |
|------|-------|
| **Timestamp** | {timestamp} |
| **Memory Files** | {memory_files} |
| **Skills** | {skills} |
| **Rules** | {rules} |
| **People** | {people} |
| **Decisions** | {decisions} |
| **Mistakes** | {mistakes} |
| **Improvements** | {improvements} |
| **Backups** | {backups} |

*Auto-generated by memory system*

"""
    
    # Read existing snapshots
    existing = ""
    if SNAPSHOT_FILE.exists():
        existing = SNAPSHOT_FILE.read_text()
    
    # Add new snapshot at top
    updated = f"# Memory System Snapshots\n\n{snapshot}{existing}"
    
    # Write back
    SNAPSHOT_FILE.write_text(updated)
    
    print(f"✅ Snapshot created: {date}")
    print(f"   Memory files: {memory_files}")
    print(f"   Skills: {skills}")
    print(f"   Rules: {rules}")

if __name__ == "__main__":
    generate_snapshot()